version: "3.1"

services:

  postgres:
    image: postgres
    ports:
      - 54321:5432
    environment:
      POSTGRES_PASSWORD: password

  adminer:
    image: adminer
    ports:
      - 8080:8080
