version: "3.1"

services:
  postgres:
    image: postgres
    ports:
      - "54321:5432"
    environment:
      POSTGRES_PASSWORD: password

  maria:
    image: mariadb
    ports:
      - "33061:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
