version: "3.1"

services:

  maria:
    image: mariadb
    ports:
      - 33061:3306
    environment:
      MYSQL_ROOT_PASSWORD: password

  postgres:
    image: postgres
    ports:
      - 54321:5432
    environment:
      POSTGRES_PASSWORD: password

  adminer:
    image: adminer
    ports:
      - 8080:8080
