name: Generate TypeDoc
on:
  push:
    branches:
      - main

jobs:
  generate-typedoc:
    name: Generate TypeDoc
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node.JS
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          path: cuillere

      - name: Checkout site
        uses: actions/checkout@v3
        with:
          repository: cuillerejs/site
          path: site
          token: ${{ secrets.CUILLERE_BOT_PAT }}

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"

      - uses: actions/cache@v3
        id: yarn-cache
        with:
          path: ${{steps.yarn-cache-dir-path.outputs.dir}}
          key: node-${{matrix.node-version}}-yarn-${{ hashFiles('cuillere/yarn.lock') }}
          restore-keys: |
            node-${{matrix.node-version}}-yarn-

      - name: Install dependencies
        run: yarn --immutable
        working-directory: cuillere

      - name: Build
        run: yarn build
        working-directory: cuillere

      - name: Generate TypeDoc
        run: yarn typedoc --out ../site/api/tip
        working-directory: cuillere

      - name: Commit and push TypeDoc
        run: |
          git add .
          git diff --staged --quiet --exit-code && echo "No changes" && exit
          git config user.name "CuillereBot (github-actions)"
          git config user.email "96485385+cuillere-bot@users.noreply.github.com"
          git commit -m "📝 Generate API"
          git push
        working-directory: site
